@startuml Sequence1

actor Client

Client ->> TableTab : 1: InitializeTableTab(Manager manager)
activate TableTab



TableTab -> Manager : 1.1: GenerateDataTable()
activate Manager

Manager ->> Manager : 1.1.1: GenerateDataTable()
activate Manager #DarkSalmon

Manager ->> Manager : 1.1.2: GenerateEmptyTable()

loop for each mushroom
Manager ->> Manager : 1.1.3: table.Rows.Add(row)
end


note right 
Fill the table
rows with
information
end note

deactivate Manager

Manager --> TableTab : 1.2: table

@enduml