@startuml Sequence 2

actor Client

Client ->> Window : 1: ImportButtonClick(object, EventArgs)

activate Window
create Manager

Window -->> Manager : 1.1: Manager(Filename)
activate Manager
Manager ->> Manager : 2: load(path)

note right 
Load the information
from the CSV in the
path
end note

activate Manager #DarkSalmon
loop for each row 
Manager ->> Manager : 3: dataSet.Add(Mushroom)

end

deactivate Manager



@enduml